// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREP0ueI6rpDMJyeuPmFYwen3jovrmBvo',
    appId: '1:738792829220:web:2020e285265c10e9f443b1',
    messagingSenderId: '738792829220',
    projectId: 'classicsound-e318c',
    authDomain: 'classicsound-e318c.firebaseapp.com',
    storageBucket: 'classicsound-e318c.firebasestorage.app',
    measurementId: 'G-HNH7DFFZ02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEi4zfa_hTflCo4t29cp9BndJ6qaym-YI',
    appId: '1:738792829220:android:fa06986a96a04bc2f443b1',
    messagingSenderId: '738792829220',
    projectId: 'classicsound-e318c',
    storageBucket: 'classicsound-e318c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg7TpZ--5dccTJzCxI4uZR9Y2QCnSXSso',
    appId: '1:738792829220:ios:936003824926eb93f443b1',
    messagingSenderId: '738792829220',
    projectId: 'classicsound-e318c',
    storageBucket: 'classicsound-e318c.firebasestorage.app',
    iosBundleId: 'summer.example.classicSound',
  );
}
